###############################################################################
# © Copyright IBM Corporation 2024
###############################################################################

- hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    app_name: 'BAQSTRT'

  tasks:
    - name: 'Stop application'
      ibm.ibm_zos_core.zos_operator:
        cmd: "C {{app_name}}"
      register: zos_operator_output

    - name: Wait for application to stop
      ansible.builtin.wait_for:
        timeout: 3

    - name: 'Start application'
      ibm.ibm_zos_core.zos_operator:
        cmd: "S {{app_name}}"
