###############################################################################
# © Copyright IBM Corporation 2024
###############################################################################

- name: Search for expiring certificate and renew it.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    cert_found: false
    today: ''

  tasks:
    - name: Set variables
      ansible.builtin.set_fact:
        cert_label: "{{ cert_label | default('zosConnectServerCert2') }}"
        cert_type: "{{ cert_type | default('USER') }}" # CERTAUTH, SITE, or USER
        sign_with: "{{ sign_with | default('CERTAUTH') }}" # CERTAUTH, SITE or Self
        sign_label: "{{ sign_label | default('IBM CA') }}" # Only required if sign_with is not 'Self'
        owner_id: "{{ owner_id | default('STCUSR') }}"
        keyring: "{{ keyring | default('Keyring.ZOSCONN') }}"
        new_expiry_date: "{{ new_expiry_date | default('2025-12-31') }}"

    - name: Run health check via operator command.
      tags: search_and_renew, search, run_hc
      ibm.ibm_zos_core.zos_operator:
        cmd: "F HZSPROC,RUN,CHECK=(IBMRACF,RACF_CERTIFICATE_EXPIRATION)"

    - name: Get sysname.
      tags: search_and_renew, search, search_hc
      ansible.builtin.command:
        cmd: sysvar SYSNAME
      changed_when: false
      register: sysname

    - name: Submit job to pull health check report.
      tags: search_and_renew, search, search_hc
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ playbook_dir }}/templates/HZPRINT.j2"
        location: local
        wait_time_s: 60
      register: hc_job_output

    - name: 'Search report for {{ cert_label }}.'
      tags: search_and_renew, search, search_hc
      ansible.builtin.set_fact:
        cert_found: true
      with_items: "{{ hc_job_output.jobs.0.ddnames }}"
      when: item.content is search(cert_label)

    - name: Print whether or not certificate is expiring.
      tags: search_and_renew, search, search_hc
      ansible.builtin.debug:
        msg: "{{ cert_label }} expiring - {{ cert_found }}"

    - name: Renew certificate if it is expiring.
      when: cert_found
      block:
        - name: Get date for timestamps.
          tags: always
          ansible.builtin.command: "date '+%b%d%y'"
          register: date_result
          changed_when: false

        - name: Set variables for use in the rest of this block of tasks.
          tags: always
          ansible.builtin.set_fact:
            today: "{{ date_result.stdout }}"
            format_cert_type: "{{ 'ID(' + owner_id + ')' if cert_type == 'USER' else cert_type }}"
            format_check_cert: "{{ 'ID(' + owner_id + ')' if cert_type == 'USER' else '' }}"
            format_expiration: "{{ 'NOTAFTER(DATE(' + new_expiry_date + '))' if new_expiry_date != '' else '' }}"

        - name: Back up current certificate.
          tags: search_and_renew, renew, backup
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT EXPORT(LABEL('{{ cert_label }}')) {{ format_cert_type }} DSN('{{ ansible_user }}.CERT.{{ cert_type }}.BACKUP.{{ today }}')

        - name: Check backup certificate.
          tags: search_and_renew, renew, backup
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT CHECKCERT('{{ ansible_user }}.CERT.{{ cert_type }}.BACKUP.{{ today }}') {{ format_check_cert }}

        - name: Rekey certificate with new temporary label.
          tags: search_and_renew, renew, rekey
          ibm.ibm_zos_core.zos_tso_command:
            commands: "RACDCERT {{ format_cert_type }} REKEY(LABEL('{{ cert_label }}')) WITHLABEL('{{ cert_label }}-NEW') {{ format_expiration }}"

        - name: List new certificate with temporary label.
          tags: search_and_renew, renew, list_new
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT {{ format_cert_type }} LIST(LABEL('{{ cert_label }}-NEW'))

        - name: Generate signing request for new certificate.
          tags: search_and_renew, renew, genreq
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT {{ format_cert_type }} GENREQ (LABEL('{{ cert_label }}-NEW')) DSN('{{ ansible_user }}.CSR.{{ cert_type }}.{{ today }}')
          when: sign_with != 'Self'

        - name: Sign new certificate, if not self-signed.
          tags: search_and_renew, renew, gencert
          ibm.ibm_zos_core.zos_tso_command:
            commands:
              - RACDCERT {{ format_cert_type }} GENCERT ('{{ ansible_user }}.CSR.{{ cert_type }}.{{ today }}') SIGNWITH({{ sign_with }} LABEL('{{ sign_label }}')) {{ format_expiration }}
          when: sign_with != 'Self'

        - name: Rollover certificate.
          tags: search_and_renew, renew, rollover
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT {{ format_cert_type }} ROLLOVER(LABEL('{{ cert_label }}')) NEWLABEL('{{ cert_label }}-NEW')

        - name: Delete old certificate.
          tags: search_and_renew, renew, delete
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT {{ format_cert_type }} DELETE(LABEL('{{ cert_label }}'))

        - name: Relabel new certificate to old name.
          tags: search_and_renew, renew, relabel
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT {{ format_cert_type }} ALTER(LABEL('{{ cert_label }}-NEW')) NEWLABEL('{{ cert_label }}')

        - name: Issue setropts refresh
          tags: refresh
          ibm.ibm_zos_core.zos_tso_command:
            commands: SETROPTS RACLIST(DIGTCERT) REFRESH

        - name: List renewed certificate with old label.
          tags: search_and_renew, renew, list_old_label
          ibm.ibm_zos_core.zos_tso_command:
            commands: RACDCERT {{ format_cert_type }} LIST(LABEL('{{ cert_label }}'))